import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalView: {
      backgroundColor: "white",
      borderRadius: 20,
      padding: 35,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
      width: 366,
      height: 393,
    },
    repModalView: {
      backgroundColor: "white",
      borderRadius: 20,
      padding: 20,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
      width: 366,
      height: 393,
    },
    modalText: {
      marginBottom: 15,
      textAlign: "center",
      fontSize: 24,
      fontWeight: '500',
      width: 233,
      height: 68,
    },
    closeButton: {
      position: 'absolute',
      top: 20,
      right: 20,
    },
    backButton: {
      position: 'absolute',
      top: 25,
      left: 25,
    },
    optionContainer: {
      backgroundColor: '#344054',
      width: 291,
      height: 97,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 30,
    },
    modalContainer: {
      width: 216,
      height: 68,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    someTextStyle: {
      marginLeft: 10,
      textAlign: "center",
      fontSize: 20,
      fontWeight: '500',
      color: '#FFFFFF',
      width: 165,
      height: 52,
    },
      bugDescription: {
      width: 304,
      height: 130,
      borderColor: '#D4D4D8',
      borderWidth: 1,
      marginTop: 20,
      marginBottom: 30,
      textAlign: 'left',
      textAlignVertical: 'top',
      padding: 13,
    },
    bugTitle: {
        borderColor: '#D4D4D8',
        borderWidth: 1,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 10,
        width: 304,
        height: 50,
        textAlign: 'left',
        textAlignVertical: 'top',
        padding: 13,
    },
    feedbackDescription: {
    width: 304,
    height: 130,
    borderColor: '#D4D4D8',
    borderWidth: 1,
    marginTop: 20,
    marginBottom: 30,
    textAlign: 'left',
    textAlignVertical: 'top',
    padding: 13,
  },
  feedbackTitle: {
      borderColor: '#D4D4D8',
      borderWidth: 1,
      fontWeight: 'bold',
      marginTop: 20,
      marginBottom: 10,
      width: 304,
      height: 50,
      textAlign: 'left',
      textAlignVertical: 'top',
      padding: 13,
  },
    saveButton: {
      backgroundColor: '#FD9F10',
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
      height: 50,
      width: '90%',
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: 0.15, 
      shadowRadius: 4, 
      elevation: 2, 
      marginBottom: 20,
    },
    saveText: {
      color: '#fff', 
      fontSize: 18,
      fontWeight: 'bold',
    },
});
